# TURN Server Listening Configuration
listening-port=3478
alt-listening-port=0

# Security Credentials Configuration
lt-cred-mech
use-auth-secret
static-auth-secret=coturn_prod_secret
realm=anon-chat.org

# Logging details
verbose
log-file=/var/log/turnserver.log
simple-log

# Network constraints
no-stdout-log
no-loopback-peers
no-multicast-peers
userdb=/var/tmp/turnuserdb.db
