version = 5.7.0
archive_dir = /etc/letsencrypt/archive/anonlink.online
cert = /etc/letsencrypt/live/anonlink.online/cert.pem
privkey = /etc/letsencrypt/live/anonlink.online/privkey.pem
chain = /etc/letsencrypt/live/anonlink.online/chain.pem
fullchain = /etc/letsencrypt/live/anonlink.online/fullchain.pem
[renewalparams]
account = b71049165d6213983cfc7a07743db97e
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
anonlink.online = /var/www/certbot
www.anonlink.online = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-07-08T12:48:49
